### ISSUE TITLE
I2C

### ISSUE THREAD

**Issue by sokart** [ms-iot/galileo-sdk#134]
Hello,
I am trying to call: Wire.requestFrom(10, 6, TRUE);
However I am getting the following error:

First-chance exception at 0x77500F63 in a.exe: Microsoft C++ exception: _arduino_fatal_error at memory location 0x0017EFC8.

Sketch Aborted! A fatal error has occurred:
Error encountered performing queued I2C transfers to address: 0x0A, Error: 0x00000457
The program '[0x89C] a.exe' has exited with code 1 (0x1).

**Comment by JustAddWires** [comment]
Hello,
Are you performing a write to the I2C device before performing the read?
If so, does the write fail or succeed?
The wire library does not have an error return on reads, but it does on writes--so a bit more information is available on write failures.
Many I2C devices expect a write operation (to set the address of the register to be read) immediately before a read operation.

**Comment by sokart** [comment]
I will try the write operation before read but have a look to the simple code that I am using; see the following link:
http://www.arduino.cc/en/Tutorial/MasterReader

**Comment by JustAddWires** [comment]
The most likely potential problem I could see with the MasterReader code is that the slave must be running and ready before the master code is started.
Also, as I suspect you already know, address 0x02 will not work with the Galileo code.  The "I2C Specification" specifies that addresses 0x00-0x07 (as well a block of addresses at the top of the 7-bit address range) are reserved for special uses on the bus--they should not be used for I2C devices.  Since you are using 0x0A, this should not be a problem.  Of course, your slave must use the same address...
I am assuming you are using an Arduino for the slave device, since Galileo doesn't support I2C slave mode.

**Comment by sokart** [comment]
I found the issue: The two devices have to share the same ground!

**Comment by ooeygui** [comment]
I'm glad you found the issue :-)

Goodl uck!
